### ISSUE TITLE
Enable US datacenters

### ISSUE THREAD

**Issue by allcentury** [commercetools/commercetools-sunrise-java-starter#26]
I don't currently see a way to override auth url / api url via environment var's found here: https://github.com/commercetools/commercetools-sunrise-java-starter/blob/aeb752c9af9526ac27bb1ac234260bea311c7a9b/conf/prod.conf or https://github.com/commercetools/commercetools-sunrise-java-starter/blob/43da4b50f8f9685e757816a00ac39237747d4213/app.json

**Comment by schleichardt** [comment]
Thanks for reporting, for now you can use this as 'prod.conf' workaround:

```
include "application"

application.setup.enabled = false
application.metrics.enabled = false

# The project key for your commercetools platform project.
ctp.projectKey = ${CTP_PROJECT_KEY}

# The client ID of your commercetools platform project.
ctp.clientId = ${CTP_CLIENT_ID}

# The client secret of your commercetools platform project.
ctp.clientSecret = ${CTP_CLIENT_SECRET}

#ctp.authUrl and ctp.apiUrl are already known as properties, so no code changes necessary
ctp.authUrl = ${CTP_AUTH_URL}
ctp.apiUrl = ${CTP_API_URL}
```

or even hardcode them for the US (snippet):

```
ctp.apiUrl = "https://api.commercetools.co"
ctp.authUrl = "https://auth.commercetools.co"
```

**Comment by mmoelli** [comment]
@allcentury As far as I can see it, this is possible now. Can we close this issue? If so, feel free,

**Comment by allcentury** [comment]
Thanks!
