### ISSUE TITLE
When using the heroku button, the logo is not displayed properly

### ISSUE THREAD

**Issue by mmoelli** [commercetools/commercetools-sunrise-java-starter#9]
The image links seems to be broken.

**Comment by lauraluiz** [comment]
@mmoelli the image link used is broken:
https://github.com/commercetools/commercetools-sunrise-java-starter/blob/master/app.json#L5
Do we have some public logo we can use here?

**Comment by mmoelli** [comment]
We should use this one: https://github.com/commercetools/press-kit/blob/master/PNG/72DPI/CT%20logo%20vertical%20RGB%2072dpi.png

Can we use an image deep link from github?

**Comment by lauraluiz** [comment]
Yep, and it is fixed now :)
